### PR TITLE
Plot FMS

### PR DESCRIPTION
**Pull request by borcuttjahns**

### CODE REVIEW

**Comment by borcuttjahns** [comment]
figureThomson2
I plotted the factor similarity score for the Thomson dataset and found that the plateau slash elbow in the curve happens super quickly (subplot a in attached figure). I'm not sure if I'm doing this incorrectly or if this is just a harsh metric - if you get the chance let me know if this is what you had envisioned @aarmey

**Comment by aarmey** [comment]
Interesting! I'll look through this carefully and provide some thoughts...

**Comment by aarmey** [comment]
A few questions/ideas:

1. How long does this take to run? I ask because it influences how much we can iterate/experiment with this.
2. There is an argument for skipping a mode when calculating the factor match score. I'd try skipping each factor one by one—their effect is multiplied together, so if the score goes up when you leave one out, that might suggest more uncertainty in those factors.
3. Try setting `consider_weights` to False.
4. If these don't lead anywhere, I would be interested in the congruence_product for each component. If you look at the factor match score code, it is the average score across components. I wonder if some match well, while others match poorly. If so, which do/don't match would be interesting to know.

**Comment by aarmey** [comment]
I couldn't wait, and ended up trying these things. They didn't really change the results. Therefore, I would suggest taking a rank where the FMS starts to drop (~4-5 components?) and then manually going through the factors and seeing what is different.

**Comment by borcuttjahns** [comment]
Sounds good thanks for taking a look. Just a heads up I’m showing my parents around for the long weekend so I’ll take care of this on Monday.

**Comment by aarmey** [comment]
Yeah, not expecting you to look before then! I'm just taking notes here. :-)

**Pull request merged**
