### PR TITLE
Need to fix annotation for cells

### PR DESCRIPTION
**Pull request by andrewram4287**
Fix Annotation for Thomson cells

### CODE REVIEW

**Comment by andrewram4287** [comment]
@borcuttjahns even with the new changes the plots looks the same

Screenshot 2023-10-24 at 11 25 53 AM

**Comment by borcuttjahns** [comment]
Agh that's frustrating it worked for me last night but now I'm seeing the same thing you are. Will mess around with this more.

**Comment by borcuttjahns** [comment]
Wait it looks in the last PR you reverted a some of the plots/changes Meyer had made to plotUMAp.py; did you want to do this? I managed to fix it with that code; I can also make the accompanying changes here but just let me know which version of the file we want to go with! (Points vs. plotUmapLabels function)

**Comment by andrewram4287** [comment]
> plotUmapLabels



> Wait it looks in the last PR you reverted a some of the plots/changes Meyer had made to plotUMAp.py; did you want to do this? I managed to fix it with that code; I can also make the accompanying changes here but just let me know which version of the file we want to go with! (Points vs. plotUmapLabels function)

Yeah that would be awesome to make changes to the main branch using plotUmapLabels

**Comment by borcuttjahns** [comment]
Ok great will be on that today!

**Comment by andrewram4287** [comment]
> Ok great will be on that today!

I believe your changes are included in the main branch so I don't know why its not working

**Comment by borcuttjahns** [comment]
Closing this - fixed it on another branch!

**Pull request closed without merging**
