### PR TITLE
plot ROC AUC of logistic model

### PR DESCRIPTION
**Pull request by pascoesean**
plotting ROC AUC of logistic regression to compare to perez et al. needs to be fixed for leaky data before final assessment of AUC.

### CODE REVIEW

**Comment by andrewram4287** [comment]
@pascoesean This looks good to me, did we want a similar structure for logreg. for randomized samples too?

**Comment by pascoesean** [comment]
> @pascoesean This looks good to me, did we want a similar structure for logreg. for randomized samples too?

Do you mean just taking random groups from all of the 355 samples for training/testing? I don't think that would help (since you'll always likely have batch/individual leakage between test/train) and those models usually end up with an ROC AUC of 1 😵‍💫.

**Comment by andrewram4287** [comment]
> > @pascoesean This looks good to me, did we want a similar structure for logreg. for randomized samples too?
> 
> Do you mean just taking random groups from all of the 355 samples for training/testing? I don't think that would help (since you'll always likely have batch/individual leakage between test/train) and those models usually end up with an ROC AUC of 1 😵‍💫.

I thought I recalled a conversation that we wanted to see how the model performed when we took a random sample of patients and tried to predict sample status (making sure we weren't duplicating any patients)

**Comment by pascoesean** [comment]
> > > @pascoesean This looks good to me, did we want a similar structure for logreg. for randomized samples too?
> > 
> > 
> > Do you mean just taking random groups from all of the 355 samples for training/testing? I don't think that would help (since you'll always likely have batch/individual leakage between test/train) and those models usually end up with an ROC AUC of 1 😵‍💫.
> 
> I thought I recalled a conversation that we wanted to see how the model performed when we took a random sample of patients and tried to predict sample status (making sure we weren't duplicating any patients)

Hmmm yeah I think that might be what I played around with before settling on a final version of `testPf2Ranks` (in #184 )-- that function lets you choose which variable you are using to make groups to cross validate, which I ran with (separately) batches and patients as grouping factors. Both were viable, but grouping by batches performed a bit worse so I did that as the final version to be more strict

**Review by aarmey — APPROVED** [review]
This all looks good to me.

**Pull request merged**
