### PR TITLE
Remove the sorting step

### PR DESCRIPTION
**Pull request by aarmey**
This should still fix the older issue where the cell weights were all scrambled.

### CODE REVIEW

**Comment by aarmey** [comment]
@borcuttjahns @andrewram4287 can you take a look at this? I'm seeing strange PaCMAP results, but don't think anything has changed. I can't figure out anything that would be wrong with the code.

**Comment by borcuttjahns** [comment]
Going to try to tackle this now.

**Comment by andrewram4287** [comment]
I doubled checked that the results for rearranging the projections and the embeddings for PaCMAP were the same, depending on how we reordered the data, so that is not the issue. The only issue that might come up with is the new preprocessing we have for the Thomson and citeseq dataset. I tried rerunning the Pf2 algorithm using our old import functions from before but I am receiving the current error

  File "/home/aramirez/scCP/.venv/lib/python3.11/site-packages/parafac2/parafac2.py", line 77, in parafac2_nd
    C = randomized_svd(covM, rank, random_state=rng, n_iter=4)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aramirez/scCP/.venv/lib/python3.11/site-packages/numpy/linalg/linalg.py", line 121, in _raise_linalgerror_svd_nonconvergence
    raise LinAlgError("SVD did not converge")
numpy.linalg.LinAlgError: SVD did not converge

**Comment by aarmey** [comment]
Thanks @andrewram4287. I agree the issue is with the data import, so I'm going to merge this.

**Comment by aarmey** [comment]
> I doubled checked that the results for rearranging the projections and the embeddings for PaCMAP were the same, depending on how we reordered the data, so that is not the issue. The only issue that might come up with is the new preprocessing we have for the Thomson and citeseq dataset. I tried rerunning the Pf2 algorithm using our old import functions from before but I am receiving the current error
> 
> File "/home/aramirez/scCP/.venv/lib/python3.11/site-packages/parafac2/parafac2.py", line 77, in parafac2_nd C = randomized_svd(covM, rank, random_state=rng, n_iter=4)[0] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/aramirez/scCP/.venv/lib/python3.11/site-packages/numpy/linalg/linalg.py", line 121, in _raise_linalgerror_svd_nonconvergence raise LinAlgError("SVD did not converge") numpy.linalg.LinAlgError: SVD did not converge

Check that there are no NaN's in the data before this. This should essentially never happen unless the data has infs or Nans.

**Pull request merged**
