### PR TITLE
plot weights from many models

### PR DESCRIPTION
**Pull request by pascoesean**
updates figure S3b, which plots weights in logistic regression towards predicting SLE status, such that any observation can be predicted given an observation and a level within that observation to predict (predictions are all binary)

### CODE REVIEW

**Comment by pascoesean** [comment]
example: 

figureS3b_

**Comment by andrewram4287** [comment]
@pascoesean The legend of this graph is a bit confusing here. What are you trying to predict for the LogReg?

**Comment by pascoesean** [comment]
figureS3b_tv

Does this make more sense? It's binary so whatever the target variable is it's just deciding if a sample is that or not that

**Comment by andrewram4287** [comment]
@pascoesean Now this makes sense to me! Maybe add a description to sccp/figures/figureS3b.py of what the plot will make. Just want to make everything more clear!

**Pull request closed without merging**
