### PR TITLE
Saving cell types for scRNAseq data

### PR DESCRIPTION
**Pull request by andrewram4287**
Saving the cell types for scRNAseq data, optional to change offset ratio

### CODE REVIEW

**Review by aarmey — COMMENTED** [review]
This all looks good. @andrewram4287 do you have poetry installed differently somehow? I'm wondering why the lock file changes so much...

**Comment by andrewram4287** [comment]
> This all looks good. @andrewram4287 do you have poetry installed differently somehow? I'm wondering why the lock file changes so much...

I have tried to add scanpy via poetry, but Im getting these errors. I had to add poetry locally in order for it scanpy to be installed

Screen Shot 2023-01-24 at 9 03 40 AM
Screen Shot 2023-01-24 at 9 03 51 AM

**Comment by aarmey** [comment]
Aha. scanpy isn't working in Python 3.10 (it's only test with 3.7, which is only supported for another couple months). You only use scanpy occasionally though, right? If it's only used for preprocessing then we can put the code that uses it in a special place.

**Review by aarmey — APPROVED** [review]
I think this will build. Merge if it does.

**Pull request merged**
