### PR TITLE
Add previous transformation of Thomson data

### PR DESCRIPTION
**Pull request by andrewram4287**
Adding previous import of Thomson dataset

### CODE REVIEW

**Comment by andrewram4287** [comment]
@aarmey After using the old transformation of the Thomson dataset, the clustering and assignments work well. How should we proceed for the import function? The previous pre-processing definitely cluster cells much better so I feel like it makes more sense to use that even though they are not built in scanpy functions.

**Comment by aarmey** [comment]
Thanks for fixing my mess! Let's bring back the old import. Please tag me on the PR when you have it copied back.

**Comment by andrewram4287** [comment]
> Thanks for fixing my mess! Let's bring back the old import. Please tag me on the PR when you have it copied back.

Should we repeat the process for the CITEseq dataset? Or have 2 versions of transforming raw counts?

**Comment by aarmey** [comment]
Use the same process and function for both.

**Pull request merged**
