### PR TITLE
Test

### PR DESCRIPTION
**Pull request by andrewram4287**

### CODE REVIEW

**Comment by andrewram4287** [comment]
@aarmey Let me know if this is more of what you were looking for

**Comment by aarmey** [comment]
Yes, but you want to use this test to call a function you write with the right interface (like I described on Slack). I don't see that here.

**Comment by andrewram4287** [comment]
> Yes, but you want to use this test to call a function you write with the right interface (like I described on Slack). I don't see that here.

Do you mean use the tests to check if it’s in the correct thesis lab format, alter the format to be used in Pf2 and output the results in Anndata?

**Comment by aarmey** [comment]
I think you're right. (1) You need a function that matches the Theis lab function format, and calls Pf2, returning the projections in the right format. (2) The unit test should call the function to test that it works.

**Comment by andrewram4287** [comment]
> I think you're right. (1) You need a function that matches the Theis lab function format, and calls Pf2, returning the projections in the right format. (2) The unit test should call the function to test that it works.



> I think you're right. (1) You need a function that matches the Theis lab function format, and calls Pf2, returning the projections in the right format. (2) The unit test should call the function to test that it works.

Hows this now?

**Comment by aarmey** [comment]
I think this is right with the additional changes I've made. I'm now trying to get it to work with the rest of the pipeline.

**Comment by aarmey** [comment]
I had to move this code over into the pipeline repository, so I'm just going to close this. Thanks for the help.

**Pull request closed without merging**
