### PR TITLE
Keep data on CPU until specific conditions are needed

### PR DESCRIPTION
**Pull request by aarmey**
I *believe* this should scale better, by keeping all the data off the GPU until each condition is needed for solving. Please try this out and see if you hit memory allocation errors. If you do, I'd appreciate information about the circumstances (screen shot of the error, what you ran, rank).

### CODE REVIEW

**Comment by andrewram4287** [comment]
@aarmey No errors on my end! For the Thompson dataset, trying out ranks 25, 40 and 80, the time it takes to run takes much longer for me.

**Comment by pascoesean** [comment]
@aarmey Also looks like its running for me-- definitely longer runtimes, but so far that seems ~ proportional with the increase in data that is being fed to the model anyways. 30 components on all of the lupus data with `n_iter_max = 200` is threatening 30-45min for running the model, but I can always do fewer iterations (at least initially). Very exciting that it works + thank you!!

**Comment by aarmey** [comment]
@pascoesean, Andrew can show you how to save the results to a file, so that you just need to run the factorization once. That way, you can save a high-iteration result, but quickly access it for further exploration.

**Comment by andrewram4287** [comment]
> @pascoesean, Andrew can show you how to save the results to a file, so that you just need to run the factorization once. That way, you can save a high-iteration result, but quickly access it for further exploration.

Sounds good! One of the tests for comparing Pf2 to tensorly did not pass, should we be concerned?

**Comment by aarmey** [comment]
I'll fix this and then merge.

**Pull request merged**
