### PR TITLE
scRNAseq R2X

### PR DESCRIPTION
**Pull request by andrewram4287**
Saving R2X values for PCA and printing lowest and highest values for Pf2

### CODE REVIEW

**Review by aarmey — CHANGES_REQUESTED** [review]
The plot shows Pf2 explains 100% of the variance with 1 comp. That can't be right...

**Comment by andrewram4287** [comment]
> The plot shows Pf2 explains 100% of the variance with 1 comp. That can't be right...

Ok I can run it again and see what's the issue.

**Comment by andrewram4287** [comment]
> The plot shows Pf2 explains 100% of the variance with 1 comp. That can't be right...

I ran it again and got the same results....

**Comment by aarmey** [comment]
That *can't* be right. What have you done to check your code?

(Note that `_parafac2_reconstruction_error` returns the sqrt of the error, not the squared error.)

**Comment by andrewram4287** [comment]
> 

Can you elaborate what you mean by "check your code"?

**Comment by aarmey** [comment]
You have a situation here where the result cannot possibly be correct. Therefore, there is an error somewhere in the code that you have written. You have to find out where that is. The best place to start is by printing out intermediate values throughout the analysis, and checking that they match your expectations. Where do the results start to not make sense?

By doing this, I can tell you that the error is you are expecting `_parafac2_reconstruction_error` returns the squared error, when if you look at the code for that function it returns the square root. Consequently, your R2X calculation is wrong.

**Pull request closed without merging**
