### PR TITLE
PCA lupus

### PR DESCRIPTION
**Pull request by andrewram4287**

### CODE REVIEW

**Comment by andrewram4287** [comment]
@aarmey This is the R2X plot for the Thomson dataset and the lupus dataset looks very similar. I'm trying to see why Pf2 isn't doing as well as before?

Screenshot 2024-04-16 at 5 26 43 PM

**Comment by aarmey** [comment]
Weird. Are the factors noticeably different?

**Comment by aarmey** [comment]
P.S. This should be added as a test—i.e. that rank 20 has above a certain R2X. We do this for ranks 1, 2, 3, but clearly that wasn't good enough to catch issues.

**Comment by aarmey** [comment]
I'd also use poetry to swap out the parafac2 solver for a few of the older commits, and see if the plot changes: https://github.com/meyer-lab/parafac2/commits/main/

If that fixes it then I broke something over there.

**Comment by aarmey** [comment]
You know what... I don't think we've looked at R2X since we fixed the normalization for read depth. Notice that the values for PCA are also much lower. I think this is simply the right results.

I just confirmed that this is not due to recent changes in the Pf2 solver.

**Comment by andrewram4287** [comment]
> You know what... I don't think we've looked at R2X since we fixed the normalization for read depth. Notice that the values for PCA are also much lower. I think this is simply the right results.
> 
> I just confirmed that this is not due to recent changes in the Pf2 solver.

Yeah we have not looked at R2X in a while. Ok I will update both plots for Thomson and Perez

**Pull request closed without merging**
