### PR TITLE
With the better memory management, we can probably run the builds in parallel

### PR DESCRIPTION
**Pull request by aarmey**

### CODE REVIEW

**Comment by aarmey** [comment]
@andrewram4287 it looks like Figure 3a is broken—`data` is undefined. Please fix this here.

**Comment by andrewram4287** [comment]
> @andrewram4287 it looks like Figure 3a is broken—`data` is undefined. Please fix this here.

Should be fixed!

**Comment by aarmey** [comment]
@andrewram4287 looks like Fig. 3c is broken now.

**Comment by aarmey** [comment]
Great. Thanks.

**Pull request merged**
