### PR TITLE
Add dense Pf2 version and udpate plots to use updated Pf2 lupus output

### PR DESCRIPTION
**Pull request by andrewram4287**
Add dense Pf2 version and udpate plots to use updated Pf2 lupus output

### CODE REVIEW

**Comment by andrewram4287** [comment]
@aarmey The prediction ability seems to have gone way down, we would we like to through the optimization process again?
Screenshot 2023-12-07 at 9 26 00 AM

**Comment by andrewram4287** [comment]
> How much time does fitting 40 comps take? I'll prob switch to building the factors live, first. That way it'll be faster to iterate.

No more than a few minutes

**Comment by andrewram4287** [comment]
@aarmey I'm now getting this error for some reason for trying to run figureLupus7, I believe the indexing for the conditions might be off now?
Screenshot 2023-12-07 at 12 33 26 PM

**Comment by aarmey** [comment]
@andrewram4287 Great, thanks! I'll look into where the predictions are going awry.

**Comment by aarmey** [comment]
Will post on Slack about this. Merging!

**Pull request merged**
