### PR TITLE
Annotation of Thomson Data

### PR DESCRIPTION
**Pull request by borcuttjahns**

### CODE REVIEW

**Comment by borcuttjahns** [comment]
@andrewram4287 @aarmey I've included a new Leiden-based annotation of the Thomson dataset at two depths. The first depth should be very similar to what we had before, and the second includes 13 cell types. I'd be happy to talk about how I did this, how I selected cell types and markers etc. in case you're interested; for now I just wanted to make sure this was ok with both of you before I merge since it'll affect some of the figures.

**Comment by aarmey** [comment]
@borcuttjahns are the Leiden numbers consistent between runs? This is what I see in the build, and the assignments seem strange to me...

Screenshot 2023-10-23 at 4 49 31 PM

**Comment by borcuttjahns** [comment]
@aarmey Huh the # of clusters is the same, and I set the random seed of neighbors as well as leiden so it _should_ be fine but you're right that labeling isn't correct...I'll look into it.

**Comment by aarmey** [comment]
If it's not something obvious let me know and I'll dig through the Leiden code to see what I can find.

**Comment by borcuttjahns** [comment]
This seems to be a compatibility thing with the points function since the native scanpy embeddings plot recovers cell types without trouble. Not sure how the colors are getting disordered but will try to fix.

**Comment by aarmey** [comment]
Aha! I tried to rip out a lot of code... I bet the color legend is just being made wrong there.

**Comment by andrewram4287** [comment]
I tried investigating if you changed anything critical for the plotting @Aaron, but everything seems to be the same... I plotted the same cell type figure for the lupus and citseq dataset and everything seems to be correct. I checked the count of the cell types via np.unique() for the Thomson dataset after gateThomsonCells, and it seems to be correct as well.

**Comment by borcuttjahns** [comment]
Ok I fixed it; it just had to do with the type of the new cell type labels being passed not being sortable as it was a categorical or something like that so I added a sorting step and passed the arguments in as an array. A little weird but assuming it doesn't break the Lupus/Cite set it should work for now! For all other intents and purposes the labels should be correct too it was just the plot not agreeing with their typing

**Pull request merged**
