### PR TITLE
plot top genes from a component

### PR DESCRIPTION
**Pull request by pascoesean**
adds functions to `geneontology.py` and common to make a barplot of the top up and down regulated genes for a certain component, then color them using a GO term that is enriched in that group. Here are two examples:

figureS4c_comp13
figureS4c_comp26

(also accepting color palette recommendations)

### CODE REVIEW

**Comment by andrewram4287** [comment]
@pascoesean Usually a lot of genes fall in more than 1 GO term. Did you find that as well? Also, many genes fall into your neither category, do you think this plot helps you interpret any of these genes?

**Comment by pascoesean** [comment]
@andrewram4287 I only chose to do one GO term for each because of potential overlap-- the original plot idea was to just plot genes and weights (all bars would be the same color), as a way to show weights without just listing genes or giving a list of enriched gene sets (which I feel like is a bit more removed/more malleable than the raw outputs). Because there is overlap between GO terms, you have to choose just one for the top and bottom subsections, and the function lets you choose which one to highlight of the top 10 terms enriched for that category. 

I think in an ideal world, I'd color all of the bars by GO term (i.e. have no neither category), but I think that gets confusing in the case that one gene falls into multiple GO terms (the assumption here being that that won't happen between the top/bottom most genes, which I feel is reasonable). This way, though, we can directly highlight any trends were finding in the gene data + specifically where we found them in the Pf2 output

**Comment by andrewram4287** [comment]
@aarmey What do you think?

**Comment by aarmey** [comment]
I agree that the link between genes and GO terms is muddled here. I also don't like that you don't get a full view of any particular GO term—if you care about GO term X, are the genes shown 1% or 90% of the genes in that term?

How about just making a plot where one GO term is shown, and every gene in that term is plotted by its weight on a component? That way you get a full view of that GO term and component's relationship.

**Comment by pascoesean** [comment]
Thoughts about something like this @andrewram4287 @aarmey :?

figureS4c_v2_comp13

This plots all the genes it can find in our set of 2,000 from a GO term (with suggested GO terms coming from those that are overrepresented in the most highly weighted genes). Biggest concern is that I'm using the [biomart API](https://gseapy.readthedocs.io/en/latest/gseapy_example.html?highlight=biomart#Biomart-API) to get a list of genes from a GO term, which seems to be maybe not as good as [the actual program](http://www.ensembl.org/biomart/martview/) (there are some discrepancies between the list of genes you get from the API and the list of genes you get from the actual program for the same GO accession #).

**Comment by aarmey** [comment]
This is great! What is the red dotted line?

**Comment by pascoesean** [comment]
> This is great! What is the red dotted line?

They represent the max/min weight value for that component-- the idea was to give an idea of the scale (for the second one you could imagine that the bars would look a lot bigger if they didn't have the same scale set by the max/min) (lines 649-650 and 660-661 in common.py)

**Comment by aarmey** [comment]
Ah, makes sense. I like keeping a consistent scaling like this.

**Pull request closed without merging**
