### PR TITLE
Creating initial code to run R2X

### PR DESCRIPTION
**Pull request by andrewram4287**
Creating code to calculate error between parafac2 and tensor, also created code to save error to plot R2X plots

### CODE REVIEW

**Comment by andrewram4287** [comment]
@aarmey should `_parafac2_rec_error()` give an error that's between 0 and 1? That's currently not the case.

**Comment by aarmey** [comment]
No, this function returns the sum of squared error. You have to divide by the overall dataset error to get the fraction unexplained, and then take 1 minus that for R2X.

**Comment by aarmey** [comment]
P.S. You don't necessarily need to use R2X. Just plotting error would be fine, too.

**Comment by andrewram4287** [comment]
@aarmey for the function` _parafac2_rec_error()`, there is a current error. Does the projections need to be rearranged into a 3-mode tensor as well, since we rearranged the tensor?

**Comment by andrewram4287** [comment]
> @aarmey for the function` _parafac2_rec_error()`, there is a current error. Does the projections need to be rearranged into a 3-mode tensor as well, since we rearranged the tensor?

Nevermind found the other function to do that!

**Comment by andrewram4287** [comment]
> function returns the sum of squared error. You have to divide by the overall dataset error to get the fraction unexplained, and then take 1 minus that for R2X

@aarmey I attempted to solve for this, but the function seems to far off from 0 to 1

**Comment by aarmey** [comment]
Just plot error for now.

**Comment by andrewram4287** [comment]
@aarmey Made the changes!

**Review by aarmey — APPROVED** [review]

**Pull request merged**
